nam = input("Damola is busy thinking about K-Drama. Not sure?")
print(nam)
nam = input("Let's check his last conversation")
print(nam)
nam = input("How far the fee?")
print("What", nam)
nam = input("This was Damola's last conversation")
print(nam)
print("Damola is a 🐐")
